
name = "the-frame-station"
compatibility_date = "2026-08-13"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "the-frame-station"
database_id = "08edcb36-6195-48dd-80b7-dda264fa0b30"
